version: '3'
services:
  sikb-postgres:
    image: postgres:11.1
    hostname: postgres
    container_name: sikb-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sikb
