language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11

dist: trusty

cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - POSTGRES_DB=sikb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5432

before_install:
  # Fix install Postgres 10
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo service postgresql restart 10
  # Create database
  - psql -c 'create database sikb;' -U postgres
  # init database with structure
  - psql -U postgres -d sikb -a -f /home/travis/build/alexeil/sikb-api/persistence/src/main/resources/initdb.sql
  - psql -U postgres -d sikb -a -f /home/travis/build/alexeil/sikb-api/persistence/src/main/resources/initData.sql
  # list all databases
  - psql -l

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
