language: java

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432

before_script:
  - psql -c 'create database sikb;' -U postgres

script:
- mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
