version: '2'
services:
  postgres:
    image: postgres:11.1
    hostname: postgres
    container_name: sikb-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sikb
    #  volumes:
    #   - ./../../persistence/src/main/resources/initdb.sql:/docker-entrypoint-initdb.d/init.sql
